### ISSUE TITLE
btclib.mnemonic_from_raw_entropy claims i passed less than 128-bit entropy

### ISSUE THREAD

**Issue by suwmr** [fametrano/btclib#15]
> The function bip39.mnemonic_from_raw_entropy() calls bip39.entropy_from_raw_entropy(), which calls entropy.str_from_entropy() which attempts to convert the integer using [this](https://github.com/fametrano/btclib/blob/master/btclib/entropy.py#L44) function which is broken. 

Any leading 0 gets stripped resulting in a <128-bit int at least half of the times

full reference for problem and possible solution [here ](https://stackoverflow.com/questions/55211270/why-does-btclib-mnemonic-from-raw-entropy-claim-i-passed-it-less-than-128-bits-o)

**Comment by fametrano** [comment]
thank you for the report.
Losing leading zeros was compliant with Electrum entropy->mnemonic behaviour, but resulted into a bug for BIP39.
It is fixed now on master branch.
