### ISSUE TITLE
how to get bip32 private key for say m/0'/0'/12 ?

### ISSUE THREAD

**Issue by shalakhin** [fametrano/btclib#16]
Thank you for the great library! Even with not a lot of examples, I have found tests pretty useful.

How can I generate or get the private key for the generate BIP32 address?

**Comment by fametrano** [comment]
with next release (later this month or early February, check the current master branch) you can use wif_from_xprv:
```
from btclib import bip32
from btclib.wif import p2pkh_address_from_wif
seed = b"00"*32  # better be random
rxprv = bip32.rootxprv_from_seed(seed)
path = "m/0h/0h/12"
xprv = bip32.derive(rxprv, path)
wif = bip32.wif_from_xprv(xprv)
address = p2pkh_address_from_wif(wif)
address2 = bip32.address_from_xpub(bip32.xpub_from_xprv(xprv))
```
with WIF being b'KyLk7s6Z1FtgYEVp3bPckPVnXvLUWNCcVL6wNt3gaT96EmzTKZwP' and both addresses being b'1Lbn3TbfPzM5AjQn84d4bugQN8W4bS1WAQ'
